export const FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS';
export const FETCH_AUTH_FAIL = 'FETCH_AUTH_FAIL';

export const ADD_NOTE = 'ADD_NOTE';
export const SET_ACTIVE_NOTE = 'SET_ACTIVE_NOTE'; 
export const SET_UNACTIVE = 'SET_UNACTIVE';